config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  draw(:users)

  get :privacy_policy, to: 'home#privacy_policy'

  resources :products

  resource :cart, only: :show do
    collection do
      get :counter
      delete :clean
    end
  end

  resources :orderables, only: :destroy do
    collection do
      post 'add'
      post 'remove'
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
# frozen_string_literal: true

class Cart < ApplicationRecord
  belongs_to :user

  has_many :orderables, dependent: :destroy
  has_many :products, through: :orderables

  def total
    orderables.to_a.sum(&:total)
  end
end

app/models/orderable.rb
# frozen_string_literal: true

class Orderable < ApplicationRecord
  belongs_to :product
  belongs_to :cart

  validates :quantity, presence: true, numericality: { greater_than: 0 }
  validates :product_id, uniqueness: { scope: :cart_id }

  def total
    product.price * quantity
  end
end

app/models/product.rb
# frozen_string_literal: true

class Product < ApplicationRecord
  extend FriendlyId
  friendly_id :name, use: :slugged

  has_many_attached :images do |attachable|
    attachable.variant :medium, resize_to_limit: [800, 800]
  end

  has_many :orderables, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0 }

  scope :newest_first, -> { order(updated_at: :desc) }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  attr_accessor :_rucaptcha

  after_create_commit :create_cart!

  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable, :lockable,
         :omniauthable, omniauth_providers: %i[google_oauth2]

  has_one :cart, dependent: :destroy

  validates :privacy_policy, acceptance: true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  include ErrorsHandlers::NotFound

  def current_cart
    current_user.cart
  end
  helper_method :current_cart
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  def show; end

  def counter
    render partial: 'counter'
  end

  def clean
    current_cart.orderables.clear

    redirect_to root_path, status: :see_other
  end
end

app/controllers/concerns/errors_handlers/not_found.rb
# frozen_string_literal: true

module ErrorsHandlers::NotFound
  extend ActiveSupport::Concern

  included do
    rescue_from ActiveRecord::RecordNotFound, with: :notfound
  end

  private

  def notfound(exception)
    logger.warn(exception)
    render file: 'public/404.html', status: :not_found, layout: false
  end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  skip_before_action :authenticate_user!

  def index; end
  def privacy_policy; end
end

app/controllers/orderables_controller.rb
# frozen_string_literal: true

class OrderablesController < ApplicationController
  def destroy
    Orderable.destroy_by(id: params[:id])
  end

  def add
    current_cart.orderables.find_or_initialize_by(product_id: permitted_params[:product_id]).tap do |orderable|
      orderable.update!(quantity: permitted_params[:quantity])
    end
  end

  def remove
    current_cart.orderables.find_by(product_id: permitted_params[:product_id]).tap do |orderable|
      next if orderable.blank?

      (orderable.quantity -= permitted_params[:quantity].to_i).tap do |quantity|
        quantity.positive? ? orderable.update!(quantity:) : orderable.destroy!
      end
    end
  end

  private

  def permitted_params
    params.require(:orderable).permit(*%i[product_id quantity])
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

class ProductsController < ApplicationController
  include Pagy::Backend

  skip_before_action :authenticate_user!, only: %i[index]
  before_action :set_product, only: %i[show edit update destroy]

  def index
    @query = Product.newest_first.ransack(params[:query])
    @pagy, @products = pagy(@query.result(distinct: true))
  end

  # def show; end

  def new
    @product = Product.new
  end

  # def edit; end

  def create
    @product = Product.new(product_params)

    if @product.save
      flash.now[:notice] = 'Product was successfully created.'
      redirect_to @product
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      flash.now[:notice] = 'Product was successfully updated.'
      redirect_to @product
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @product.destroy
    flash.now[:notice] = 'Product was successfully destroyed.'
    redirect_to root_path, status: :see_other
  end

  private

  def set_product
    @product = Product.friendly.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :price, images: [])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  invisible_captcha only: %i[create]
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def google_oauth2
    Users::GoogleOauth2.new(request.env['omniauth.auth']).build_user.then do |user|
      if user.save
        sign_out_all_scopes
        flash[:notice] = t('devise.omniauth_callbacks.success', kind: 'Google')
        sign_in_and_redirect user, event: :authentication
      else
        failure
      end
    end
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  invisible_captcha only: %i[create update]
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  invisible_captcha only: %i[create]
  before_action :configure_sign_up_params, only: %i[create]
  before_action :configure_account_update_params, only: %i[update]

  protected

  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[privacy_policy])
  end

  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: %i[name])
  end

  def after_inactive_sign_up_path_for(_resource)
    new_session_path(resource_name)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  invisible_captcha only: %i[create]

  protected

  def after_sign_out_path_for(_resource_or_scope)
    new_session_path(resource_name)
  end

  def after_sign_in_path_for(resource_or_scope)
    stored_location_for(resource_or_scope) || root_path
  end
end

app/controllers/users/turbo_devise_controller.rb
# frozen_string_literal: true

module Users
  class TurboDeviseController < ApplicationController
    class Responder < ActionController::Responder
      def to_turbo_stream
        controller.render(options.merge(formats: :html))
      rescue ActionView::MissingTemplate => e
        raise e if get?

        if has_errors? && default_action
          render rendering_options.merge(formats: :html, status: :unprocessable_entity)
        else
          redirect_to navigation_location
        end
      end
    end

    self.responder = Responder
    respond_to :html, :turbo_stream
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  invisible_captcha only: %i[create]
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/views/carts/_counter.html.slim
= turbo_frame_tag :cart_counter do
  .badge.text-bg-light
    = number_to_currency(current_cart.total)

app/views/carts/show.html.slim
= render 'shared/root' do
  h1 Cart
  = link_to clean_cart_path, data: { turbo_frame: :_top, turbo_method: :delete, turbo_confirm: t('confirm') }, class: 'btn btn-outline-danger btn-sm' do
    = render Icon::BaseComponent.new(klass: 'cart-x').with_content('Clear')

  table.table.table-hover.table-bordered.table-sm.caption-top
    caption List of products
    thead
      tr
        th scope='col' #
        th scope='col' Name
        th scope='col' Price
        th scope='col' Quantity
        th scope='col' Total
        th scope='col'
    tbody
      - current_cart.orderables.each do |orderable|
        tr
          th scope='row' = orderable.id
          td = orderable.product.name
          td = number_to_currency(orderable.product.price)
          / td = orderables.quantity
          td
            .d-flex
              = render Orderables::Forms::AddComponent.new(product: orderable.product)
              = render Orderables::Forms::RemoveComponent.new(product: orderable.product)
          td = number_to_currency(orderable.total)
          td = link_to orderable_path(orderable), data: { turbo_method: :delete }, class: 'btn' do
            = render Icon::BaseComponent.new(klass: 'x-lg')
    tfoot.table-group-divider
      tr
        td colspan='4' Total
        td = number_to_currency(current_cart.total)

app/views/home/index.html.slim
= render 'shared/root' do
  = turbo_frame_tag :products_page, src: products_path, loading: :lazy, class: 'd-block container' do
    .d-flex.justify-content-center
      = render LoaderComponent.new

app/views/home/privacy_policy.html.slim
= render 'shared/root' do
  .container
    h1 Privacy Policy for Eight and a half percent
    p At Eight and a half percent, accessible from #{link_to root_url, root_url}, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by Eight and a half percent and how we use it.
    p If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.
    p
      | This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in Eight and a half percent. This policy is not applicable to any information collected offline or via channels other than this website. Our Privacy Policy was created with the help of the
      =< link_to 'Free Privacy Policy Generator', 'https://www.privacypolicygenerator.info/', target: '_blank', rel: 'noopener'
    h2 Consent
    p By using our website, you hereby consent to our Privacy Policy and agree to its terms.
    h2 Information we collect
    p The personal information that you are asked to provide, and the reasons why you are asked to provide it, will be made clear to you at the point we ask you to provide your personal information.
    p If you contact us directly, we may receive additional information about you such as your name, email address, phone number, the contents of the message and/or attachments you may send us, and any other information you may choose to provide.
    p When you register for an Account, we may ask for your contact information, including items such as name, company name, address, email address, and telephone number.
    h2 How we use your information
    p We use the information we collect in various ways, including to:
    ul
      li Provide, operate, and maintain our website
      li Improve, personalize, and expand our website
      li Understand and analyze how you use our website
      li Develop new products, services, features, and functionality
      li Communicate with you, either directly or through one of our partners, including for customer service, to provide you with updates and other information relating to the website, and for marketing and promotional purposes
      li Send you emails
      li Find and prevent fraud
    h2 Log Files
    p Eight and a half percent follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information.
    h2 Cookies and Web Beacons
    p Like any other website, Eight and a half percent uses 'cookies'. These cookies are used to store information including visitors' preferences, and the pages on the website that the visitor accessed or visited. The information is used to optimize the users' experience by customizing our web page content based on visitors' browser type and/or other information.
    h2 Advertising Partners Privacy Policies
    p You may consult this list to find the Privacy Policy for each of the advertising partners of Eight and a half percent.
    p Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on Eight and a half percent, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.
    p Note that Eight and a half percent has no access to or control over these cookies that are used by third-party advertisers.
    h2 Third Party Privacy Policies
    p Eight and a half percent's Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options.
    p You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites.
    h2 CCPA Privacy Rights (Do Not Sell My Personal Information)
    p Under the CCPA, among other rights, California consumers have the right to:
    p Request that a business that collects a consumer's personal data disclose the categories and specific pieces of personal data that a business has collected about consumers.
    p Request that a business delete any personal data about the consumer that a business has collected.
    p Request that a business that sells a consumer's personal data, not sell the consumer's personal data.
    p If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
    h2 GDPR Data Protection Rights
    p We would like to make sure you are fully aware of all of your data protection rights. Every user is entitled to the following:
    p The right to access – You have the right to request copies of your personal data. We may charge you a small fee for this service.
    p The right to rectification – You have the right to request that we correct any information you believe is inaccurate. You also have the right to request that we complete the information you believe is incomplete.
    p The right to erasure – You have the right to request that we erase your personal data, under certain conditions.
    p The right to restrict processing – You have the right to request that we restrict the processing of your personal data, under certain conditions.
    p The right to object to processing – You have the right to object to our processing of your personal data, under certain conditions.
    p The right to data portability – You have the right to request that we transfer the data that we have collected to another organization, or directly to you, under certain conditions.
    p If you make a request, we have one month to respond to you. If you would like to exercise any of these rights, please contact us.
    h2 Children's Information
    p Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.
    p Eight and a half percent does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.

app/views/layouts/application.html.slim
doctype html
html.h-100
  head
    title = Rails.application.class.module_parent_name.underscore.humanize
    meta content='width=device-width,initial-scale=1' name='viewport'
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', 'data-turbo-track': 'reload'
    = javascript_include_tag 'application', 'data-turbo-track': 'reload', defer: true

    = favicon_link_tag asset_path('gem.svg')
  body.h-100.d-flex.flex-column
    = render 'shared/header'
    main.flex-grow-1
      = yield
    = render 'shared/footer'

app/views/orderables/_form.html.slim
= simple_form_for(:orderable, url: path) do |f|
  = f.hidden_field :product_id, value: product.id
  = f.input :quantity, input_html: { value: 1, maxlength: 1 }
  = f.button :submit, '+'

app/views/orderables/add.turbo_stream.erb
<%= turbo_stream.update :cart_counter do %>
  <%= render 'carts/counter' %>
<% end %>

app/views/orderables/remove.turbo_stream.erb
<%= turbo_stream.update :cart_counter do %>
  <%= render 'carts/counter' %>
<% end %>

app/views/products/_form.html.slim
= simple_form_for product do |f|
  = f.input :name
  = f.input :price
  = f.input :images, input_html: { multiple: true, direct_upload: true }

  = render Button::SubmitFormComponent.new(f).with_content('Update')

app/views/products/edit.html.slim
= turbo_frame_tag @product, class: 'd-block container' do
  .d-flex.justify-content-between
    = render Button::BackComponent.new
    = link_to @product, class: 'btn btn-outline-primary btn-sm' do
      = render Icon::BaseComponent.new(klass: 'arrow-up-right-circle').with_content('View details')

  h1 Editing product

  = render 'form', product: @product

app/views/products/index.html.slim
= turbo_frame_tag :products_page, class: 'd-block container' do
  .row.gy-3.row-cols-1
    .col
      h1 Products
    .col
      = link_to 'New product', new_product_path, class: 'btn btn-primary'
    .col
      = search_form_for @query, data: { turbo_frame: :collection, turbo_action: :advance, controller: 'form', action: 'input->form#submit' } do |f|
        .input-group.mb-3
          = f.search_field :name_cont, class: 'form-control', placeholder: t('search')
    .col
      = turbo_frame_tag :collection, class: 'row row-cols-1 gy-4' do
        .col
          .row.gy-4
            = render EmptyContentComponent.new
            = render ProductComponent.with_collection(@products)
        .col
          .row.justify-content-center
            .col-auto
              = render PagyComponent.new(pagy: @pagy)

app/views/products/new.html.erb
<h1>New product</h1>

<%= render "form", product: @product %>

<br>

<div>
  <%= link_to "Back to products", products_path %>
</div>

app/views/products/show.html.slim
= turbo_frame_tag :products_page, class: 'd-block container' do
  .row.row-cols-1
    .col
      .d-flex.justify-content-between
        = render Button::BackComponent.new
        .btn-group.btn-group-sm
          = link_to edit_product_path(@product), class: 'btn btn-outline-primary' do
            = render Icon::BaseComponent.new(klass: 'pencil-square').with_content('Edit')
          = link_to @product, data: { turbo_method: :delete, turbo_confirm: t('confirm'), turbo_frame: :_top }, class: 'btn btn-outline-primary' do
            = render Icon::BaseComponent.new(klass: 'trash').with_content('Destroy')
    .col
      = render ProductComponent.new(product: @product)
    - if @product.images.any?
      .col
        #carouselExampleCaptions.carousel.slide data-bs-ride="false"
          .carousel-indicators
            button.active aria-current="true" aria-label=("Slide 1") data-bs-slide-to="0" data-bs-target="#carouselExampleCaptions" type="button"
            - @product.images.offset(1).size.times do |i|
              button aria-label=("Slide #{i.next}") data-bs-slide-to=i.next.next data-bs-target="#carouselExampleCaptions" type="button"
          .carousel-inner
            .carousel-item.active
              - @product.images.first.then do |image|
                = image_tag image, loading: 'lazy', class: 'img d-block w-100'
            - @product.images.offset(1).each do |image|
              .carousel-item
                = image_tag image, loading: 'lazy', class: 'img d-block w-100'
          - if @product.images.many?
            button.carousel-control-prev data-bs-slide="prev" data-bs-target="#carouselExampleCaptions" type="button"
              span.carousel-control-prev-icon aria-hidden="true"
              span.visually-hidden Previous
            button.carousel-control-next data-bs-slide="next" data-bs-target="#carouselExampleCaptions" type="button"
              span.carousel-control-next-icon aria-hidden="true"
              span.visually-hidden Next

app/views/shared/_footer.html.slim
footer
  .py-3.my-4.border-top
    ul.nav.justify-content-center
      li.nav-item
        = link_to t('home'), root_path, data: { turbo_frame: :root, turbo_action: :advance }, class: 'nav-link px-2 text-muted'
      li.nav-item
        = link_to t('privacy_policy'), privacy_policy_path, data: { turbo_frame: :_self }, class: 'nav-link px-2 text-muted'
    ul.nav.justify-content-center
      li.nav-item
        = link_to '#', class: 'nav-link px-2 text-dark' do
          = render Icon::BaseComponent.new(klass: 'twitter')
      li.nav-item
        = link_to '#', class: 'nav-link px-2 text-dark' do
          = render Icon::BaseComponent.new(klass: 'instagram')
      li.nav-item
        = link_to '#', class: 'nav-link px-2 text-dark' do
          = render Icon::BaseComponent.new(klass: 'facebook')
    .text-center
      small.text-muted © #{Date.current.year} Company, Inc

app/views/shared/_header.html.slim
header
  nav.navbar.navbar-expand-lg.navbar-light.bg-white.mb-5.border-bottom.sticky-top
    .container
      = link_to root_path, data: { turbo_frame: :root, turbo_action: :advance }, class: 'navbar-brand' do
        = render Icon::BrandComponent.new
      button.navbar-toggler aria-controls='navbarText' aria-expanded='false' aria-label='Toggle navigation' data-bs-target='#navbarText' data-bs-toggle='collapse' type='button'
        span.navbar-toggler-icon
      #navbarText.collapse.navbar-collapse
        ul.navbar-nav.me-auto.mb-2.mb-lg-0
          / li.nav-item
          /   = link_to 'Products', '#', class: 'nav-link'
        ul.nav.nav-pills.mb-2.mb-lg-0
          - if user_signed_in?
            li.nav-item
              .row.gx-2
                .col.my-auto
                  = turbo_frame_tag :cart_counter, src: counter_cart_path, loading: :lazy do
                    = render LoaderComponent.new(size_klass: 'sm')
                .col
                  = link_to cart_path, data: { turbo_frame: :root, turbo_action: :advance }, class: 'btn btn-primary' do
                    = render Icon::BaseComponent.new(klass: 'cart2')
            li.nav-item.dropdown.ms-3
              a.dropdown-toggle.nav-link aria-expanded='false' data-bs-toggle='dropdown' href='#' role='button'
                = render Icon::UserComponent.new(user: current_user)
              ul.dropdown-menu
                li
                  = link_to edit_user_registration_path, class: 'dropdown-item', data: { turbo_frame: :root, turbo_action: :advance } do
                    = render Icon::BaseComponent.new(klass: 'pencil-square').with_content('Edit')
                li
                  hr.dropdown-divider
                li
                  = button_to destroy_user_session_path, method: :delete, class: 'dropdown-item' do
                    = render Icon::BaseComponent.new(klass: 'escape').with_content('Sign out')
          - else
            li.nav-item
              = link_to new_user_registration_path, data: { turbo_frame: :root, turbo_action: :advance }, class: 'nav-link' do
                = render Icon::Devise::RegistrationComponent.new
            li.nav-item
              = link_to new_user_session_path, data: { turbo_frame: :root, turbo_action: :advance }, class: 'nav-link active' do
                = render Icon::Devise::SessionComponent.new

app/views/shared/_root.html.slim
= turbo_frame_tag :root do
  - unless devise_controller?
    .container
      = render NotificationsComponent.new
  = yield